"""
AI Solver Module

This module is my implementation of the AI Solver for the other Group's Minesweeper game. 
I started by creating a version of the easy-AI mode, so I could build upon it and make the medium-AI mode.
The hard-AI mode is still under development, and I wanted to talk to other group members before moving on.

The AI doesn't touch pygame ore the mouse at all, it just calls the same Board methods a real player's click would trigger
like the reveal/toggle flag, using row/col cords actions

Author: Jett Viduya, Emilia Davis

Claude Sonnet 5.5 was used to assist with the development of the hard_move (1-2-1) function, all the code generated has been proofread and understood by Emilia before being added.
Any joining of code generated by AI and human code has been done by Emilia, no copilot or in-line editors were used.
"""

from minebrute import Minebrute
import random

#this function returns every valid row/col touching a cell, this mirrors the Board._neighbors() function
#I wanted to have our own copy here so the AI can use it since it should be private from the Board class
def get_neighbors(board, r, c):
    neighbors = []
    for dr in (-1, 0, 1):
        for dc in (-1, 0, 1):
            if dr == 0 and dc == 0:
                continue   #skip the actual cell itself, I only need 8 adjacent cells around it
            nr, nc = r + dr, c + dc
            if 0 <= nr < board.size and 0 <= nc < board.size:
                neighbors.append((nr, nc))
    return neighbors


#function to return every row/col the AI will be allowed to use/click on
#any cell that isn't already opened and doesn't have a flag on it will be considered valid for the AI to click on

def get_valid_moves(board):
    valid_moves = []
    for r in range(board.size):
        for c in range(board.size):
            if not board.revealed[r][c] and not board.flagged[r][c]:
                valid_moves.append((r, c))
    return valid_moves


#easy difficulty AI: no strategy, just picks random legal cell and opens it.
#returns the row/col of the chosen cell, or none if the board is finished/every cell is flagged

def ai_easy_move(board):
    valid_moves = get_valid_moves(board)
    if not valid_moves:
        return None

    r, c = random.choice(valid_moves)
    board.reveal(r,c)
    return (r, c)


#medium difficulty AI: this has the basic strategy  of the two logic rules from the spec before falling back to a random click
#rule 1 = look at a revealed #. If the # of hidden neighbors = equals that #, every one of those should be a mine --> so just flag all of it
#rule 2 = look at a revealed #. If the # of flagged neighbors = that #, every other hidden neighbor should be safe --> so just reveal all of them

#we only read board.counts for the cells that are already revealed. Reading that # on a hidden cell would sorta be cheating and the player can't see that
#returns true if the AI made a move either normal/random, false if there were no legal moves left

#scan the board looking a revealed # and the AI applies the two rules

def apply_medium(board):
    for r in range(board.size):
        for c in range(board.size):
            if not board.revealed[r][c]:
                continue  #skip hidden cells, we only apply rules to revealed numbers

            number = board.counts[r][c]
            if number == 0:
                continue  #skip cells with 0, they have no useful information for the AI

            neighbors = get_neighbors(board, r, c)
            hidden_neighbors = [(nr, nc) for nr, nc in neighbors if not board.revealed[nr][nc]]
            flagged_neighbors = [(nr, nc) for nr, nc in neighbors if board.flagged[nr][nc]]
            unflagged_neighbors = [(nr, nc) for nr, nc in hidden_neighbors if not board.flagged[nr][nc]]

            #nothing left to do if there are no hidden neighbors
            if not unflagged_neighbors:
                continue

            #rule 1: if the number of hidden neighbors equals the number on the cell, flag all hidden neighbors
            if len(hidden_neighbors) == number:
                for nr, nc in unflagged_neighbors:
                    board.toggle_flag(nr, nc)
                return True  # rule 1 applied suc2essfully


            #rule 2: enough flags around a revealed number means all other hidden neighbors are safe to reveal
            if len(flagged_neighbors) == number:
                for nr, nc in unflagged_neighbors:
                    board.reveal(nr, nc)
                    if board.game_over:
                        return True  # stop early if that move ended the game
                return True  # rule 2 applied suc2essfully
    return False

def ai_medium_move(board): # split up apply_medium_move into its rules and application so i could use it for hard moves (without the easy part)
    if apply_medium(board):
        return True

    #if we get here, no rules could be applied, so fall back to a random move
    return ai_easy_move(board) is not None

def get_unknown_neighbors(board, r, c):
    # makes a set of coordinates and returns them for all neighbors that are not revealed or flagged.
    return {(nr, nc) for nr, nc in get_neighbors(board, r, c) if not board.revealed[nr][nc] and not board.flagged[nr][nc]}

def get_remaining_mines(board, r, c):
    # sums up all flagged nearby cells
    flagged = sum(1 for nr, nc in get_neighbors(board, r, c) if board.flagged[nr][nc])
    # return number of nearby mines - flagged cells
    return board.counts[r][c] - flagged

def in_bounds(board, r, c):
    # just checks if the coordinate is inside the board
    return 0 <= r < board.size and 0 <= c < board.size

def apply_121_rule(board):
    for r in range(board.size):
        for c in range(board.size):
            if not board.revealed[r][c]:
                continue
            
            # make note of left, middle, right cells in both horizontally and vertically
            for dr, dc in ((0, 1), (1, 0)):
                left = (r - dr, c - dc)
                mid = (r, c)
                right = (r + dr, c + dc)

                # check if left and right are in bounds
                if not in_bounds(board, *left) or not in_bounds(board, *right):
                    continue

                # check if left and right are revealed
                if not board.revealed[left[0]][left[1]]:
                    continue
                if not board.revealed[right[0]][right[1]]:
                    continue

                # makes sure left, middle, and right line up to a 1-2-1
                if get_remaining_mines(board, *left) != 1:
                    continue
                if get_remaining_mines(board, *mid) != 2:
                    continue
                if get_remaining_mines(board, *right) != 1:
                    continue

                pr, pc = dc, dr

                for s in (1, -1):
                    a1 = (left[0] + s * pr, left[1] + s * pc) # check cell next to left
                    b2 = (mid[0] + s * pr, mid[1] + s * pc) # check cell next to middle
                    c3 = (right[0] + s * pr, right[1] + s * pc) # check cell next to right

                    # if any of the above are out of bounds, skip
                    if not (in_bounds(board, *a1) and
                            in_bounds(board, *b2) and
                            in_bounds(board, *c3)):
                        continue

                    # if any of the above are not unknown, skip
                    if a1 not in get_unknown_neighbors(board, *left):
                        continue 
                    if b2 not in get_unknown_neighbors(board, *mid):
                        continue
                    if c3 not in get_unknown_neighbors(board, *right):
                        continue

                    # if everything is true, flag a1
                    if not board.flagged[a1[0]][a1[1]]:
                        board.toggle_flag(a1[0], a1[1])
                    # same with c3
                    if not board.flagged[c3[0]][c3[1]]:
                        board.toggle_flag(c3[0], c3[1])
                    # and reveal b2
                    board.reveal(b2[0], b2[1])
                    return True

    return False # else default to easy (random) move


def ai_hard_move(board):
    if apply_medium(board): # applies medium rules
        return True
    if apply_121_rule(board): # applies 1-2-1 rule
        return True
    return ai_easy_move(board) is not None # defaults


# Brute force hard difficulty AI: This scans tiles and finds all locations which are definitely safe or definitely have a mine.
# Returns True if a move was made (i.e. a tile is revealed), and False if no move was made.
# If no new information is present on the board, a random tile is clicked.

def ai_brute_force_move(board):
    algo = Minebrute(board)
    confirmedSafe = set()
    confirmedMines = set()
    for r in range(board.size):
        for c in range(board.size):
            safe, mines = algo.minebrute((r, c), maxCombinations=100)
            confirmedMines = confirmedMines.union(mines)
            confirmedSafe = confirmedSafe.union(safe)
    # Temporary pass so I can have a breakpoint here:
    pass
    # Mark all flagged locations with flags
    for mine in confirmedMines:
        board.flagged[mine[0]][mine[1]] = True
    # Click all confirmed safe tiles
    if len(confirmedSafe) > 0:
        for safe in confirmedSafe:
            board.reveal(safe[0], safe[1])
        return True
    else:
        # Default to easy AI behavior
        return ai_easy_move(board) is not None